/* NaviarCare — Doctor roster (NC_DOCTORS)
 * Single source of truth used by booking.html, admin.html, and profile.html.
 *
 * To update: Admin panel (admin.html) → Doctors tab → export → replace this file → git commit → Vercel redeploys.
 */
const NC_DOCTORS = [
  {
    id: 'ak', initials: 'AK', name: 'Dr. Ayşe Kaya',
    specialty: 'general-practice', specialtyLabel: 'General practice',
    experience: 14,
    langs: ['tr', 'en', 'de'],
    langLabels: { tr: 'Türkçe', en: 'English', de: 'Deutsch' },
    types: ['video', 'written'],
    available: 'now',
    bio: 'GP with 14 years in primary care. Helps patients understand which specialist they need and prepares them for the referral process.',
  },
  {
    id: 'mp', initials: 'MP', name: 'Dr. María Pérez',
    specialty: 'internal-medicine', specialtyLabel: 'Internal medicine',
    experience: 9,
    langs: ['es', 'en'],
    langLabels: { es: 'Español', en: 'English' },
    types: ['video', 'written'],
    available: 'now',
    bio: 'Internal medicine specialist. Guides patients through complex symptom presentations and explains which diagnostic pathway to follow.',
  },
  {
    id: 'as', initials: 'AS', name: 'Dr. Ama Sarpong',
    specialty: 'pediatrics', specialtyLabel: 'Paediatrics',
    experience: 11,
    langs: ['en'],
    langLabels: { en: 'English' },
    types: ['video'],
    available: 'now',
    bio: 'Paediatric specialist helping families understand child health concerns and navigate to the right department quickly.',
  },
  {
    id: 'rk', initials: 'RK', name: 'Dr. Rahul Kumar',
    specialty: 'cardiology', specialtyLabel: 'Cardiology',
    experience: 18,
    langs: ['en', 'hi'],
    langLabels: { en: 'English', hi: 'हिन्दी' },
    types: ['video', 'written'],
    available: 'soon',
    bio: 'Cardiologist with 18 years in outpatient clinics. Advises on cardiac symptoms and helps patients understand whether they need urgent or routine referral.',
  },
  {
    id: 'ev', initials: 'EV', name: 'Dr. Elena Volkov',
    specialty: 'dermatology', specialtyLabel: 'Dermatology',
    experience: 7,
    langs: ['ru', 'en'],
    langLabels: { ru: 'Русский', en: 'English' },
    types: ['written'],
    available: 'now',
    bio: 'Dermatologist specialising in routing advice for skin concerns. Helps patients distinguish what needs urgent attention from what can wait.',
  },
  {
    id: 'fo', initials: 'FO', name: 'Dr. Fatima Omar',
    specialty: 'general-practice', specialtyLabel: 'General practice',
    experience: 6,
    langs: ['ar', 'en', 'so'],
    langLabels: { ar: 'العربية', en: 'English', so: 'Soomaali' },
    types: ['video', 'written'],
    available: 'now',
    bio: 'GP with a focus on patients navigating an unfamiliar health system. Fluent in Arabic and Somali.',
  },
  {
    id: 'bc', initials: 'BC', name: 'Dr. Büşra Çelik',
    specialty: 'psychiatry', specialtyLabel: 'Mental health',
    experience: 8,
    langs: ['tr', 'en', 'de'],
    langLabels: { tr: 'Türkçe', en: 'English', de: 'Deutsch' },
    types: ['video', 'written'],
    available: 'now',
    bio: 'Psychiatrist helping patients navigate mental health pathways. Routes patients to the right therapy type, service, or level of care.',
  },
  {
    id: 'ln', initials: 'LN', name: 'Dr. Lars Nybø',
    specialty: 'general-practice', specialtyLabel: 'General practice',
    experience: 20,
    langs: ['no', 'en', 'de'],
    langLabels: { no: 'Norsk', en: 'English', de: 'Deutsch' },
    types: ['video'],
    available: 'now',
    bio: 'Norwegian GP with 20 years. Specialises in helping international patients navigate Norway\'s fastlege and specialist referral system.',
  },
  {
    id: 'sa', initials: 'SA', name: 'Dr. Sofia Andersen',
    specialty: 'gynecology', specialtyLabel: 'Gynaecology',
    experience: 12,
    langs: ['no', 'en', 'es'],
    langLabels: { no: 'Norsk', en: 'English', es: 'Español' },
    types: ['video', 'written'],
    available: 'soon',
    bio: 'Gynaecologist helping patients understand their symptoms and find the right specialist or clinic, in the right timeframe.',
  },
  {
    id: 'tm', initials: 'TM', name: 'Dr. Tariq Mahmoud',
    specialty: 'neurology', specialtyLabel: 'Neurology',
    experience: 15,
    langs: ['ar', 'en', 'fr'],
    langLabels: { ar: 'العربية', en: 'English', fr: 'Français' },
    types: ['written'],
    available: 'now',
    bio: 'Neurologist advising on symptom patterns and helping patients understand whether they need urgent or routine neurological investigation.',
  },
  {
    id: 'pc', initials: 'PC', name: 'Dr. Pierre Clément',
    specialty: 'orthopedics', specialtyLabel: 'Orthopaedics',
    experience: 11,
    langs: ['fr', 'en'],
    langLabels: { fr: 'Français', en: 'English' },
    types: ['video', 'written'],
    available: 'now',
    bio: 'Orthopaedic surgeon advising on musculoskeletal symptoms. Guides patients on whether physio, GP, or specialist referral is the right next step.',
  },
];
// Üst düzey const window'a yazılmaz; admin.html ve profile.html window.NC_DOCTORS okur.
window.NC_DOCTORS = NC_DOCTORS;
