import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker,{osloToUTC,verifyStripe,demandForecast} from '../dist/server/index.js';
import {texts} from '../src/locales.js';
import {contentInsights,operationMetrics} from '../src/insights.js';
function setup(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(q){let args=[];const api={bind(...a){args=a;return api},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:sql.prepare(q).run(...args)}}};return api},async batch(items){sql.exec('BEGIN');try{const result=[];for(const i of items)result.push(await i.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};
const env={DB,SITE_ORIGIN:'https://care.test',ADMIN_EMAILS:'owner@example.test',RATE_LIMIT_SECRET:'fixture'},waits=[],ctx={waitUntil(p){waits.push(p)}};
async function request(path,body,who='u1',extra={}){const headers={origin:env.SITE_ORIGIN,cookie:'naviar_csrf=fixture-token','x-csrf-token':'fixture-token','content-type':'application/json','oai-authenticated-user-id':who,'oai-authenticated-user-email':who==='admin'?'owner@example.test':'visitor@example.test',...extra};const r=await worker.fetch(new Request(env.SITE_ORIGIN+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)}),env,ctx);let data;try{data=await r.clone().json()}catch{data=await r.text()}return {status:r.status,data,response:r}}
function slot(id='s1'){const start=Date.now()+86400000;sql.prepare('INSERT INTO slots(id,start,end,demo,active) VALUES(?,?,?,?,1)').run(id,start,start+1200000,1);return id}
const payload=(slotId='s1')=>({slotId,service:'practical',relationship:'self',name:'Test User',email:'user@example.test',locale:'nb',idem:crypto.randomUUID()});return {sql,env,request,slot,payload,waits,ctx}}
test('all public routes render in three equivalent languages',async()=>{const s=setup();const keys=Object.keys(texts.nb).sort();for(const lang of ['nb','en','tr']){assert.deepEqual(Object.keys(texts[lang]).sort(),keys);for(const page of ['','/book','/contact','/enquiries','/my','/payment','/privacy','/terms']){const r=await s.request('/'+lang+page);assert.equal(r.status,200);assert.match(r.data,new RegExp('<html lang="'+lang+'"'));assert.ok(!r.data.includes('NAVIAR CARE 1'));assert.match(r.data,/hreflang="tr"/);assert.match(r.data,/NAVIAR CARE/)} }assert.equal((await s.request('/unknown')).status,404)});
test('booking persisted, replay deduplicated, slot collision rejected, and email suppressed in preview',async()=>{const s=setup();s.slot();const payload=s.payload();const a=await s.request('/api/bookings',payload);assert.equal(a.status,201);assert.equal(a.data.booking.demo,1);assert.equal((await s.request('/api/bookings',payload)).status,200);assert.equal((await s.request('/api/bookings',s.payload(),'u2')).status,409);assert.equal(s.sql.prepare('SELECT count(*) AS n FROM bookings').get().n,1);await Promise.all(s.waits);assert.equal(s.sql.prepare('SELECT state FROM outbox').get().state,'suppressed');assert.equal((await s.request('/api/slots')).data.slots.length,0)});
test('ownership boundary, cancellation and slot reuse',async()=>{const s=setup();s.slot();const b=(await s.request('/api/bookings',s.payload())).data.booking;assert.equal((await s.request('/api/bookings/'+b.id+'/cancel',{},'u2')).status,404);assert.equal((await s.request('/api/bookings',undefined,'u2')).data.bookings.length,0);assert.equal((await s.request('/api/bookings/'+b.id+'/cancel',{})).status,200);assert.equal((await s.request('/api/bookings',s.payload(),'u2')).status,201)});
test('admin authorization, CSRF, real-data preview guard and unknown inputs',async()=>{const s=setup();s.slot();assert.equal((await s.request('/api/admin/overview')).status,403);assert.equal((await s.request('/api/admin/overview',undefined,'admin')).status,200);assert.equal((await s.request('/api/bookings',s.payload(),'u1',{origin:'https://evil.test'})).status,403);assert.equal((await s.request('/api/bookings',{...s.payload(),email:'user@example.com'})).status,400);assert.equal((await s.request('/api/bookings',{...s.payload(),service:'medical'})).status,400)});
test('Oslo times reject nonexistent and ambiguous daylight-saving hours',()=>{assert.equal(new Date(osloToUTC('2026-01-10T09:00')).toISOString(),'2026-01-10T08:00:00.000Z');assert.equal(new Date(osloToUTC('2026-07-10T09:00')).toISOString(),'2026-07-10T07:00:00.000Z');assert.throws(()=>osloToUTC('2026-03-29T02:30'));assert.throws(()=>osloToUTC('2026-10-25T02:30'));assert.throws(()=>osloToUTC('2026-02-31T09:00'))});
test('overlapping coordinator times cannot be added',async()=>{const s=setup();const d=new Date(Date.now()+3*86400000).toISOString().slice(0,10);assert.equal((await s.request('/api/admin/slots',{start:d+'T10:00',duration:30},'admin')).status,201);assert.equal((await s.request('/api/admin/slots',{start:d+'T10:20',duration:20},'admin')).status,409);assert.equal((await s.request('/api/admin/slots',{start:d+'T10:40',duration:20},'admin')).status,201)});
test('analytics needs explicit permission and deduplicates without identity or form data',async()=>{const s=setup();Object.assign(s.env,{SERVICE_OPEN:'true',OPERATOR_NAME:'Fixture',SERVICE_AREA:'Fixture',CONTACT_EMAIL:'a@example.test',LAUNCH_REVIEW_COMPLETE:'true'});const event={session:crypto.randomUUID(),kind:'view',section:'services',locale:'nb',consent:true,email:'not-recorded@example.test'};assert.equal((await s.request('/api/analytics',event)).status,403);const h={cookie:'naviar_csrf=fixture-token; naviar_analytics=yes'};assert.equal((await s.request('/api/analytics',event,'u1',h)).status,200);await s.request('/api/analytics',event,'u1',h);assert.equal(s.sql.prepare('SELECT count(*) AS n FROM events').get().n,1);assert.ok(!JSON.stringify(s.sql.prepare('SELECT * FROM events').all()).includes(event.email));assert.equal((await s.request('/api/analytics',{...event,section:'private-health'},'u1',h)).status,400)});
test('contact message is durable, escaped on client and replay is deduplicated',async()=>{const s=setup(),data={name:'Test',email:'a@example.test',topic:'helper',body:'<script>alert(1)</script>',locale:'tr',idem:crypto.randomUUID()};const a=await s.request('/api/contact',data);assert.equal(a.status,201);assert.equal((await s.request('/api/contact',data)).data.id,a.data.id);assert.equal(s.sql.prepare('SELECT count(*) AS n FROM messages').get().n,1);assert.equal((await s.request('/api/admin/overview',undefined,'u2')).status,403)});
test('payments are blocked before configuration even with client supplied amount',async()=>{const s=setup();s.slot();const b=(await s.request('/api/bookings',s.payload())).data.booking;assert.equal((await s.request('/api/checkout',{id:b.id,total:1,acceptTerms:true,offerVersion:0})).status,503);assert.equal(s.sql.prepare('SELECT payment FROM bookings').get().payment,'not_requested')});
test('email provider failure remains visible and retry uses the same deduplication key',async()=>{const s=setup();s.slot();s.sql.prepare('UPDATE slots SET demo=0').run();Object.assign(s.env,{SERVICE_OPEN:'true',OPERATOR_NAME:'Fixture',SERVICE_AREA:'Fixture',CONTACT_EMAIL:'a@example.test',LAUNCH_REVIEW_COMPLETE:'true',RESEND_API_KEY:'re_fixture',EMAIL_FROM:'Care <mail@example.test>'});const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');calls.push(options);return new Response(JSON.stringify(calls.length===1?{error:'fixture'}:{id:'mail_fixture'}),{status:calls.length===1?500:200})};try{assert.equal((await s.request('/api/bookings',s.payload())).status,201);await Promise.all(s.waits);assert.equal(s.sql.prepare('SELECT state FROM outbox').get().state,'failed');assert.equal((await s.request('/api/admin/retry-email',{},'admin')).status,200);assert.equal(s.sql.prepare('SELECT state FROM outbox').get().state,'sent');assert.equal(s.sql.prepare('SELECT attempts FROM outbox').get().attempts,2);assert.equal(calls[0].headers['Idempotency-Key'],calls[1].headers['Idempotency-Key']);assert.equal(JSON.parse(calls[0].body).to[0],'user@example.test')}finally{globalThis.fetch=original}});
async function signed(raw,secret,now=Date.now()){const ts=Math.floor(now/1000);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const hash=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(ts+'.'+raw)));return 't='+ts+',v1='+Array.from(hash).map(x=>x.toString(16).padStart(2,'0')).join('')}
test('signed payment events validate raw body, time and idempotent state',async()=>{const secret='whsec_fixture';const raw='{"ok":true}',sig=await signed(raw,secret);assert.equal(await verifyStripe(raw,sig,secret),true);assert.equal(await verifyStripe(raw+' ',sig,secret),false);assert.equal(await verifyStripe(raw,await signed(raw,secret,Date.now()-600000),secret),false);const s=setup();s.slot();const booking=(await s.request('/api/bookings',s.payload())).data.booking;s.sql.prepare("UPDATE bookings SET demo=0,total=12300,offer_version=1,payment='checkout_pending',stripe_session='cs_fixture' WHERE id=?").run(booking.id);Object.assign(s.env,{STRIPE_SECRET_KEY:'sk_live_local_fixture',STRIPE_WEBHOOK_SECRET:secret,PAYMENTS_ENABLED:'true',SERVICE_OPEN:'true',OPERATOR_NAME:'Fixture',SERVICE_AREA:'Fixture',CONTACT_EMAIL:'a@example.test',LAUNCH_REVIEW_COMPLETE:'true'});const event={id:'evt_fixture',type:'checkout.session.completed',livemode:true,data:{object:{id:'cs_fixture',currency:'nok',amount_total:12300,payment_status:'paid',metadata:{booking_id:booking.id,offer_version:'1'}}}};const send=async()=>{const payload=JSON.stringify(event);return worker.fetch(new Request('https://care.test/api/webhooks/stripe',{method:'POST',headers:{'stripe-signature':await signed(payload,secret)},body:payload}),s.env,s.ctx)};assert.equal((await send()).status,200);assert.equal((await send()).status,200);assert.equal(s.sql.prepare('SELECT payment FROM bookings').get().payment,'paid');assert.equal(s.sql.prepare('SELECT count(*) AS n FROM webhook_events').get().n,1);event.id='evt_modified';event.data.object.amount_total=1;assert.equal((await send()).status,409)});
test('demand forecasting rejects empty and thin history',()=>{assert.equal(demandForecast([]).available,false);assert.equal(demandForecast([{created:Date.now()}]).available,false);const now=Date.now(),records=Array.from({length:75},(_,i)=>({created:now-(i+1)*86400000}));assert.equal(demandForecast(records,now).available,true)});
test('service guide renders equivalent choices and a descriptive title in all languages',async()=>{const s=setup();for(const lang of ['nb','en','tr']){const r=await s.request('/'+lang+'/guide');assert.equal(r.status,200);assert.ok(r.data.includes('<title>NAVIAR CARE · '+texts[lang].guide.title+'</title>'));assert.equal(texts[lang].guide.choices.length,4);assert.equal(texts[lang].guide.frequencies.length,3);assert.ok(r.data.includes('id="service-guide"'));assert.ok(r.data.includes(texts[lang].guide.privacy));assert.ok(!r.data.includes('[object Object]'));assert.equal((r.data.match(/name="need"/g)||[]).length,4)}const book=await s.request('/tr/book');assert.ok(book.data.includes('aria-current="step"'));assert.ok(book.data.includes('Adım 1 / 3'))});
test('message workflow is administrator-only, versioned, audited and rejects stale changes',async()=>{const s=setup();const m=(await s.request('/api/contact',{name:'Test',email:'a@example.test',topic:'support',body:'Question',locale:'nb',idem:crypto.randomUUID()})).data;const change={id:m.id,status:'in_progress',version:0};assert.equal((await s.request('/api/admin/message-status',change,'u1')).status,403);assert.equal((await s.request('/api/admin/message-status',{...change,status:'invented'},'admin')).status,400);assert.equal((await s.request('/api/admin/message-status',change,'admin')).status,200);assert.equal((await s.request('/api/admin/message-status',{...change,status:'closed'},'admin')).status,409);const record=s.sql.prepare('SELECT status,version,body FROM messages').get();assert.equal(record.status,'in_progress');assert.equal(record.version,1);assert.equal(record.body,'Question');assert.equal(s.sql.prepare("SELECT count(*) AS n FROM audit WHERE action='message_in_progress'").get().n,1);assert.equal((await s.request('/api/admin/message-status',{id:m.id,status:'closed',version:1},'admin')).status,200)});
test('only free future slots can be closed, and closed slots reject bookings',async()=>{const s=setup();s.slot();assert.equal((await s.request('/api/admin/close-slot',{id:'s1'},'u1')).status,403);const b=(await s.request('/api/bookings',s.payload())).data.booking;assert.equal((await s.request('/api/admin/close-slot',{id:'s1'},'admin')).status,409);await s.request('/api/bookings/'+b.id+'/cancel',{});assert.equal((await s.request('/api/admin/close-slot',{id:'s1'},'admin')).status,200);assert.equal((await s.request('/api/bookings',s.payload())).status,409);assert.equal((await s.request('/api/slots')).data.slots.length,0)});
test('closing a slot between availability lookup and insert cannot leave a booking or email',async()=>{const s=setup();s.slot();const batch=s.env.DB.batch;s.env.DB.batch=async items=>{s.sql.prepare('UPDATE slots SET active=0').run();return batch(items)};const r=await s.request('/api/bookings',s.payload());assert.equal(r.status,409);assert.equal(s.sql.prepare('SELECT count(*) AS n FROM bookings').get().n,0);assert.equal(s.sql.prepare('SELECT count(*) AS n FROM outbox').get().n,0)});
test('a removed time can be offered again without changing earlier booking history',async()=>{const s=setup();s.slot();const start=Math.floor((Date.now()+86400000)/60000)*60000,end=start+20*60000;s.sql.prepare('UPDATE slots SET start=?,end=?').run(start,end);const b=(await s.request('/api/bookings',s.payload())).data.booking;await s.request('/api/bookings/'+b.id+'/cancel',{});await s.request('/api/admin/close-slot',{id:'s1'},'admin');const value=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(start).replace(' ','T');const added=await s.request('/api/admin/slots',{start:value,duration:30},'admin');assert.equal(added.status,201);assert.notEqual(added.data.id,'s1');const old=(await s.request('/api/bookings')).data.bookings[0];assert.equal(old.end,end);assert.equal(old.status,'cancelled')});
test('operational metrics exclude test data and keep empty denominators unknown',async()=>{const s=setup();s.slot();const booking=(await s.request('/api/bookings',s.payload())).data.booking;let m=await operationMetrics(s.env);assert.equal(m.bookings.total,0);assert.equal(m.bookings.cancellationRate,null);assert.equal(m.capacity.fillRate,null);s.sql.prepare('UPDATE slots SET demo=0').run();s.sql.prepare('UPDATE bookings SET demo=0').run();m=await operationMetrics(s.env);assert.equal(m.bookings.total,1);assert.equal(m.capacity.booked,1);assert.equal(m.capacity.total,1);assert.equal(m.capacity.fillRate,1);await s.request('/api/bookings/'+booking.id+'/cancel',{});m=await operationMetrics(s.env);assert.equal(m.bookings.cancelled,1);assert.equal(m.bookings.cancellationRate,1);assert.equal(m.capacity.booked,0);s.sql.prepare('UPDATE bookings SET created=?').run(Date.now()-31*86400000);assert.equal((await operationMetrics(s.env)).bookings.total,0);const admin=await s.request('/api/admin/overview',undefined,'admin');assert.equal(admin.status,200);assert.equal(admin.data.metrics.demoExcluded,true)});
test('content review suggestions wait for adequate views and use a labelled provisional rule',()=>{assert.equal(contentInsights([]).available,false);assert.equal(contentInsights([{section:'services',views:19,engaged:0}]).available,false);const result=contentInsights([{section:'services',views:10,engaged:1},{section:'services',views:10,engaged:2},{section:'faq',views:20,engaged:6}]);assert.equal(result.available,true);assert.deepEqual(result.review,['services']);assert.equal(result.minimumViews,20);assert.equal(result.engagementThreshold,0.3)});
function checkoutFixture(){
 const s=setup();s.slot();liveFixture(s);Object.assign(s.env,{STRIPE_SECRET_KEY:'sk_live_local_fixture',STRIPE_WEBHOOK_SECRET:'whsec_fixture',PAYMENTS_ENABLED:'true'});
 // Create a preview booking before converting the isolated fixture to a live offer.
 s.env.SERVICE_OPEN='false';
 return s.request('/api/bookings',s.payload()).then(({data:{booking:b}})=>{s.env.SERVICE_OPEN='true';s.sql.prepare("UPDATE bookings SET demo=0,total=12300,offer_details='Agreed practical help',offer_version=1,payment='offered' WHERE id=?").run(b.id);return {s,b,payload:{id:b.id,total:1,acceptTerms:true,offerVersion:1},session:{id:'cs_mock',url:'https://checkout.stripe.com/c/mock',currency:'nok',amount_total:12300,livemode:true,metadata:{booking_id:b.id,offer_version:'1'},status:'open',payment_status:'unpaid'}}});
}
test('checkout uses the stored amount and retrieves known sessions even after 24 hours',async()=>{
 const {s,b,payload,session}=await checkoutFixture(),original=globalThis.fetch,calls=[];
 globalThis.fetch=async(url,options)=>{calls.push({url,...options});return new Response(JSON.stringify(session))};
 try{assert.equal((await s.request('/api/checkout',payload)).status,200);s.sql.prepare('UPDATE bookings SET checkout_started=?').run(Date.now()-48*3600000);assert.equal((await s.request('/api/checkout',payload)).status,200);assert.equal(calls.length,2);assert.equal(calls[0].body.get('line_items[0][price_data][unit_amount]'),'12300');assert.equal(calls[1].url,'https://api.stripe.com/v1/checkout/sessions/cs_mock');assert.equal(calls[1].body,undefined);assert.equal((await s.request('/api/bookings/'+b.id+'/cancel',{})).status,409)}finally{globalThis.fetch=original}
});
test('uncertain checkout retries keep the original attempt and stop before key expiry',async()=>{
 const {s,payload}=await checkoutFixture(),original=globalThis.fetch,calls=[];
 globalThis.fetch=async(url,options)=>{calls.push(options);throw new Error('Simulated lost response')};
 try{assert.equal((await s.request('/api/checkout',payload)).status,503);const first=s.sql.prepare('SELECT checkout_started FROM bookings').get().checkout_started;assert.ok(first);assert.equal((await s.request('/api/checkout',payload)).status,503);assert.equal(s.sql.prepare('SELECT checkout_started FROM bookings').get().checkout_started,first);assert.equal(calls[0].headers['Idempotency-Key'],calls[1].headers['Idempotency-Key']);
 for(const start of [Date.now()-23*3600000,null]){s.sql.prepare('UPDATE bookings SET checkout_started=?').run(start);const r=await s.request('/api/checkout',payload);assert.equal(r.status,409);assert.equal(r.data.error,'payment_review')}assert.equal(calls.length,2);assert.equal(s.sql.prepare('SELECT payment FROM bookings').get().payment,'checkout_pending')
 }finally{globalThis.fetch=original}
});
test('retrieved completed checkout stays pending and verified expiry requires renewed acceptance',async()=>{
 const {s,payload,session}=await checkoutFixture(),original=globalThis.fetch,calls=[];
 globalThis.fetch=async(url,options)=>{calls.push({url,...options});return new Response(JSON.stringify(session))};
 try{await s.request('/api/checkout',payload);session.status='complete';session.payment_status='paid';session.url=null;assert.equal((await s.request('/api/checkout',payload)).data.pending,true);assert.equal(s.sql.prepare('SELECT payment FROM bookings').get().payment,'checkout_pending');
 session.status='expired';session.payment_status='unpaid';assert.equal((await s.request('/api/checkout',payload)).data.error,'offer_changed');const b=s.sql.prepare('SELECT * FROM bookings').get();assert.equal(b.payment,'offered');assert.equal(b.offer_version,2);assert.equal(b.checkout_started,null);assert.equal((await s.request('/api/checkout',payload)).status,409);assert.equal(calls.filter(c=>c.method==='POST').length,1)
 }finally{globalThis.fetch=original}
});
test('checkout rejects provider amount, session identity and insecure redirect mismatches',async()=>{
 const original=globalThis.fetch;
 try{for(const wrong of [{amount_total:1},{livemode:false},{metadata:{}},{url:'http://checkout.stripe.com/c/mock'},{url:'https://checkout.stripe.com.attacker.test/c/mock'}]){const {s,payload,session}=await checkoutFixture();globalThis.fetch=async()=>new Response(JSON.stringify({...session,...wrong}));assert.equal((await s.request('/api/checkout',payload)).status,502);assert.equal(s.sql.prepare('SELECT payment FROM bookings').get().payment,'checkout_pending')}
 const {s,payload,session}=await checkoutFixture();s.sql.prepare("UPDATE bookings SET payment='checkout_pending',stripe_session='cs_expected'").run();globalThis.fetch=async()=>new Response(JSON.stringify(session));assert.equal((await s.request('/api/checkout',payload)).status,502)
 }finally{globalThis.fetch=original}
});
test('asynchronous payment stays pending; expiry reopens the offer and accepts webhook replays',async()=>{const s=setup();s.slot();const b=(await s.request('/api/bookings',s.payload())).data.booking;s.sql.prepare("UPDATE bookings SET demo=0,total=12300,offer_version=1,payment='checkout_pending',stripe_session='cs_fixture' WHERE id=?").run(b.id);Object.assign(s.env,{STRIPE_SECRET_KEY:'sk_live_local_fixture',STRIPE_WEBHOOK_SECRET:'whsec_fixture'});const event={id:'evt_wait',type:'checkout.session.completed',livemode:true,data:{object:{id:'cs_fixture',currency:'nok',amount_total:12300,payment_status:'unpaid',metadata:{booking_id:b.id,offer_version:'1'}}}};const send=async()=>{const raw=JSON.stringify(event);return worker.fetch(new Request('https://care.test/api/webhooks/stripe',{method:'POST',headers:{'stripe-signature':await signed(raw,'whsec_fixture')},body:raw}),s.env,s.ctx)};assert.equal((await send()).status,200);assert.equal(s.sql.prepare('SELECT payment FROM bookings').get().payment,'checkout_pending');event.id='evt_expired';event.type='checkout.session.expired';assert.equal((await send()).status,200);assert.equal((await send()).status,200);const updated=s.sql.prepare('SELECT payment,offer_version,stripe_session FROM bookings').get();assert.equal(updated.payment,'offered');assert.equal(updated.offer_version,2);assert.equal(updated.stripe_session,null)});

const liveFixture=s=>Object.assign(s.env,{SERVICE_OPEN:'true',OPERATOR_NAME:'Fixture',SERVICE_AREA:'Fixture',CONTACT_EMAIL:'a@example.test',LAUNCH_REVIEW_COMPLETE:'true'});
test('enquiries expose only the authenticated sender and carry coordinator status updates',async()=>{
 const s=setup();const create=who=>s.request('/api/contact',{name:'Test',email:'a@example.test',topic:'support',body:'A test request',locale:'tr',idem:crypto.randomUUID()},who);
 const own=await create('u1');await create('u2');let list=(await s.request('/api/enquiries')).data.messages;assert.equal(list.length,1);assert.equal(list[0].id,own.data.id);assert.equal(list[0].status,'new');assert.equal(list[0].email,undefined);assert.equal(list[0].owner,undefined);
 await s.request('/api/admin/message-status',{id:own.data.id,status:'in_progress',version:0},'admin');list=(await s.request('/api/enquiries')).data.messages;assert.equal(list[0].status,'in_progress');assert.ok(list[0].updated);assert.equal((await s.request('/api/enquiries',undefined,'')).status,401);
});
test('preview and administrator analytics are excluded; live next-step events are bounded and deduplicated',async()=>{
 const s=setup(),event={session:crypto.randomUUID(),kind:'book_click',section:'services',locale:'en',consent:true},h={cookie:'naviar_csrf=fixture-token; naviar_analytics=yes'};
 assert.equal((await s.request('/api/analytics',event,'u1',h)).data.excluded,true);liveFixture(s);assert.equal((await s.request('/api/analytics',event,'admin',h)).data.excluded,true);
 assert.equal((await s.request('/api/analytics',event,'u1',h)).status,200);await s.request('/api/analytics',event,'u1',h);assert.equal(s.sql.prepare('SELECT count(*) n FROM events').get().n,1);
 assert.equal((await s.request('/api/analytics',{...event,kind:'diagnosis_prediction'},'u1',h)).status,400);
 s.sql.prepare("INSERT INTO events(id,session,kind,section,locale,day,created) VALUES('legacy','legacy','view','services','en','2026-09-05',?)").run(Date.now());const data=(await s.request('/api/admin/overview',undefined,'admin')).data;assert.equal(data.nextSteps[0].clicks,1);assert.equal(data.events.length,0);
});
test('readiness reports missing prerequisites without exposing runtime values',async()=>{
 const s=setup();s.env.STRIPE_SECRET_KEY='sk_live_secret_fixture';const d=(await s.request('/api/admin/overview',undefined,'admin')).data;assert.equal(d.readiness.paymentKeys,false);assert.equal(d.readiness.sender,false);assert.equal(d.readiness.operator,false);assert.ok(!JSON.stringify(d).includes(s.env.STRIPE_SECRET_KEY));
});
test('retry never sends an obsolete confirmation for an already cancelled booking',async()=>{
 const s=setup();s.slot();s.sql.prepare('UPDATE slots SET demo=0').run();liveFixture(s);const b=(await s.request('/api/bookings',s.payload())).data.booking;await Promise.all(s.waits);await s.request('/api/bookings/'+b.id+'/cancel',{});await Promise.all(s.waits);
 Object.assign(s.env,{RESEND_API_KEY:'re_fixture',EMAIL_FROM:'test@example.test'});const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{calls.push(JSON.parse(options.body));return new Response(JSON.stringify({id:'fixture'}))};
 try{await s.request('/api/admin/retry-email',{},'admin');assert.equal(calls.length,1);assert.ok(calls[0].text.includes(texts.nb.cancelled));assert.equal(s.sql.prepare("SELECT state FROM outbox WHERE kind='confirm'").get().state,'superseded')}finally{globalThis.fetch=original}
});
test('forecast keeps the held-out test weeks out of method selection and names its current-week horizon',()=>{
 const now=Date.parse('2026-09-09T12:00:00Z'),stop=Date.parse('2026-09-07T00:00:00Z'),week=604800000;
 const history=counts=>counts.flatMap((n,i)=>Array.from({length:n},()=>({created:stop-(10-i)*week+86400000})));
 const a=demandForecast(history([5,6,7,8,9,10,11,12,13,14]),now),b=demandForecast(history([5,6,7,8,9,10,11,12,40,1]),now);
 assert.equal(a.method,'last_week');assert.equal(b.method,a.method);assert.equal(a.periodStart,stop);assert.equal(a.periodEnd,stop+week);assert.equal(a.evaluationWeeks,2);assert.equal(a.holdoutMAE,1);
});
test('integrated multilingual pages preserve service detail, demo labels and private enquiry navigation',async()=>{
 const s=setup();for(const lang of ['nb','en','tr']){const home=await s.request('/'+lang);assert.equal(home.status,200);assert.ok(home.data.includes(texts[lang].studio.details));assert.ok(home.data.includes('/assets/naviar-care-v03.svg'));assert.ok(home.data.includes('/'+lang+'/enquiries'));assert.equal((home.data.match(/<h1/g)||[]).length,1);const book=await s.request('/'+lang+'/book?service=social');assert.ok(book.data.includes(texts[lang].studio.demoConfirm));assert.ok(book.data.includes('/en/book?service=social'));assert.ok(book.data.includes('value="social" checked'));const none=await s.request('/'+lang+'/book');assert.ok(!none.data.includes('checked required'));const enquiry=await s.request('/'+lang+'/enquiries');assert.ok(enquiry.data.includes('<title>NAVIAR CARE · '+texts[lang].improvements.enquiries+'</title>'))}
 assert.equal((await s.request('/assets/naviar-care-v03.svg')).status,200);assert.equal((await s.request('/__preview/role/admin')).status,404);
});
