/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChuckNorrisRouteImport } from './routes/chuck-norris'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LicenseTermsRouteImport } from './routes/license-terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PlatesSlugRouteImport } from './routes/plates.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChuckNorrisRoute = ChuckNorrisRouteImport.update({
  id: '/chuck-norris',
  path: '/chuck-norris',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseTermsRoute = LicenseTermsRouteImport.update({
  id: '/license-terms',
  path: '/license-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlatesSlugRoute = PlatesSlugRouteImport.update({
  id: '/plates/$slug',
  path: '/plates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chuck-norris': typeof ChuckNorrisRoute
  '/contact': typeof ContactRoute
  '/license-terms': typeof LicenseTermsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/plates/$slug': typeof PlatesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chuck-norris': typeof ChuckNorrisRoute
  '/contact': typeof ContactRoute
  '/license-terms': typeof LicenseTermsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/plates/$slug': typeof PlatesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chuck-norris': typeof ChuckNorrisRoute
  '/contact': typeof ContactRoute
  '/license-terms': typeof LicenseTermsRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/plates/$slug': typeof PlatesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chuck-norris'
    | '/contact'
    | '/license-terms'
    | '/privacy'
    | '/refunds'
    | '/admin'
    | '/plates/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chuck-norris'
    | '/contact'
    | '/license-terms'
    | '/privacy'
    | '/refunds'
    | '/admin'
    | '/plates/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chuck-norris'
    | '/contact'
    | '/license-terms'
    | '/privacy'
    | '/refunds'
    | '/_authenticated/admin'
    | '/plates/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChuckNorrisRoute: typeof ChuckNorrisRoute
  ContactRoute: typeof ContactRoute
  LicenseTermsRoute: typeof LicenseTermsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  PlatesSlugRoute: typeof PlatesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuck-norris': {
      id: '/chuck-norris'
      path: '/chuck-norris'
      fullPath: '/chuck-norris'
      preLoaderRoute: typeof ChuckNorrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license-terms': {
      id: '/license-terms'
      path: '/license-terms'
      fullPath: '/license-terms'
      preLoaderRoute: typeof LicenseTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/plates/$slug': {
      id: '/plates/$slug'
      path: '/plates/$slug'
      fullPath: '/plates/$slug'
      preLoaderRoute: typeof PlatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChuckNorrisRoute: ChuckNorrisRoute,
  ContactRoute: ContactRoute,
  LicenseTermsRoute: LicenseTermsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  PlatesSlugRoute: PlatesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
