import {forecastContent} from './forecast.mjs';
const locales=['nb','en','tr'];
const safePages=['home','about','languages'];
const now=()=>Date.now();
const uid=()=>crypto.randomUUID();
const validId=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(x);
export class Fault extends Error{constructor(code,status=400){super(code);this.status=status;}}
function need(test,code='invalid_request',status=400){if(!test)throw new Fault(code,status);}
function db(env){need(env.DB,'storage_unavailable',503);return env.DB;}
function stmt(env,sql,...v){return db(env).prepare(sql).bind(...v);}
async function one(env,sql,...v){return stmt(env,sql,...v).first();}
async function rows(env,sql,...v){return (await stmt(env,sql,...v).all()).results;}
const json=(obj,status=200,headers={})=>new Response(JSON.stringify(obj),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
function actor(req){const id=req.headers.get('oai-authenticated-user-id');need(id,'sign_in_required',401);return {id,email:req.headers.get('oai-authenticated-user-email')||''};}
function admin(req,env){const a=actor(req);need((env.ADMIN_EMAILS||'').toLowerCase().split(',').map(x=>x.trim()).includes(a.email.toLowerCase())&&a.email,'forbidden',403);return a;}
async function body(req){need(Number(req.headers.get('content-length')||0)<=4096,'request_too_large',413);const raw=await req.text();need(raw.length<=4096,'request_too_large',413);try{return JSON.parse(raw);}catch{throw new Fault('invalid_json');}}
function strict(obj,keys){need(obj&&typeof obj==='object'&&!Array.isArray(obj));need(Object.keys(obj).every(k=>keys.includes(k)),'unexpected_field');}
function origin(req){need(req.headers.get('origin')===new URL(req.url).origin,'origin_rejected',403);need(req.headers.get('content-type')?.includes('application/json'),'json_required',415);}
function locale(l){need(locales.includes(l),'invalid_locale');return l;}
function formatDate(starts,l='en'){return new Intl.DateTimeFormat(l==='nb'?'nb-NO':l==='tr'?'tr-TR':'en-GB',{timeZone:'Europe/Oslo',dateStyle:'full',timeStyle:'short'}).format(starts);}
export function emailTemplate(kind,l,starts){const i=locales.indexOf(l);const subject={confirmation:['Testreservasjonen er lagret','Your test reservation is saved','Test rezervasyonunuz kaydedildi'],cancelled:['Testreservasjonen er avbestilt','Your test reservation is cancelled','Test rezervasyonunuz iptal edildi'],rescheduled:['Testreservasjonen er flyttet','Your test reservation has moved','Test rezervasyonunuz değiştirildi']}[kind][i];return {subject:'NAVIAR CARE 2 — '+subject,text:subject+'\n\n'+formatDate(starts,l)+' (Europe/Oslo)\n\n'+['Dette er bare en test. Ingen helsetime eller videosamtale er opprettet. Ingen betaling er belastet gjennom denne meldingen.','This is a test only. No medical appointment or video call has been created. This message does not charge a payment.','Bu yalnızca bir testtir. Gerçek sağlık randevusu veya görüntülü görüşme oluşturulmadı. Bu mesajla ödeme alınmaz.'][i]};}
export function exampleSlots(at=now()){const out=[];for(let d=1;d<=14;d++){const date=new Date(at+d*86400000);const ymd=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);const noon=Date.parse(ymd+'T12:00:00Z');const weekday=new Date(noon).getUTCDay();if(weekday===0||weekday===6)continue;const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Oslo',hour:'2-digit',hourCycle:'h23'}).format(noon));const offset=hour-12;for(const h of [10,11,13,14]){const starts=Date.parse(ymd+'T'+String(h-offset).padStart(2,'0')+':00:00Z');out.push({id:'test_'+starts,starts,ends:starts+20*60000});}}return out;}
async function getBooking(env,id,owner){need(validId(id));const b=await one(env,'SELECT b.*,s.starts,s.ends FROM bookings b JOIN slots s ON b.slot=s.id WHERE b.id=? AND b.owner=?',id,owner);need(b,'not_found',404);return b;}
async function freeSlot(env,id){need(validId(id));const s=await one(env,'SELECT * FROM slots WHERE id=? AND starts>?',id,now()+60000);need(s,'slot_unavailable',409);return s;}
async function createBooking(req,env,b){const a=actor(req);strict(b,['slot','locale','key','accept_test']);locale(b.locale);need(validId(b.key)&&b.accept_test===true,'test_acknowledgement_required');const existing=await one(env,'SELECT * FROM bookings WHERE owner=? AND key=?',a.id,b.key);if(existing){need(existing.slot===b.slot&&existing.locale===b.locale,'idempotency_conflict',409);return json({booking:existing,replayed:true});}const s=await freeSlot(env,b.slot),id=uid(),ts=now();try{const result=await db(env).batch([
stmt(env,"INSERT INTO bookings(id,owner,slot,locale,status,key,created,updated) SELECT ?,?,?,?,'active',?,?,? WHERE (SELECT count(*) FROM bookings WHERE owner=? AND status='active')<3",id,a.id,s.id,b.locale,b.key,ts,ts,a.id),
stmt(env,"INSERT INTO outbox(id,booking,kind,locale,starts,created) SELECT ?,?,'confirmation',?,?,? WHERE changes()=1",uid(),id,b.locale,s.starts,ts)
]);need(result[0].meta.changes===1,'booking_limit',409);}catch(e){if(/UNIQUE/.test(e.message)){const prior=await one(env,'SELECT * FROM bookings WHERE owner=? AND key=?',a.id,b.key);if(prior&&prior.slot===s.id&&prior.locale===b.locale)return json({booking:prior,replayed:true});throw new Fault('slot_unavailable',409);}throw e;}return json({booking:await getBooking(env,id,a.id)},201);}
async function changeBooking(req,env,id,b){const a=actor(req);strict(b,['action','slot']);const old=await getBooking(env,id,a.id);need(['cancel','reschedule'].includes(b.action));if(b.action==='cancel'&&old.status==='cancelled')return json({ok:true,replayed:true});need(old.status==='active','booking_inactive',409);const s=b.action==='reschedule'?await freeSlot(env,b.slot):old;const ts=Math.max(now(),old.updated+1),status=b.action==='cancel'?'cancelled':'active',kind=b.action==='cancel'?'cancelled':'rescheduled';if(b.action==='reschedule'){need(old.payment==='none'||old.payment.startsWith('simulated_'),'payment_in_progress',409);if(old.slot===s.id)return json({ok:true,replayed:true});}try{const r=await db(env).batch([
stmt(env,"UPDATE bookings SET slot=?,status=?,updated=?,payment=CASE WHEN ?='cancelled' AND payment='stripe_test_paid' THEN 'test_refund_review' ELSE payment END WHERE id=? AND owner=? AND status='active' AND updated=?",b.action==='cancel'?old.slot:s.id,status,ts,status,id,a.id,old.updated),
stmt(env,'INSERT INTO outbox(id,booking,kind,locale,starts,created) SELECT ?,?,?,?,?,? WHERE changes()=1',uid(),id,kind,old.locale,s.starts,ts)]);need(r[0].meta.changes===1,'booking_changed',409);}catch(e){if(/UNIQUE/.test(e.message))throw new Fault('slot_unavailable',409);throw e;}return json({ok:true});}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
function same(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let v=0;for(let i=0;i<a.length;i++)v|=a.charCodeAt(i)^b.charCodeAt(i);return v===0;}
async function consentState(req,env){const val=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('nc_consent='))?.slice(11);if(!val||!env.CONSENT_SECRET)return {choice:'unset'};const [choice,ts,id,sig]=val.split('.');if(!['accepted','rejected'].includes(choice)||!validId(id)||!/^\d+$/.test(ts)||now()-Number(ts)>180*86400000||Number(ts)>now())return {choice:'unset'};if(!same(sig,await hmac(env.CONSENT_SECRET,choice+'.'+ts+'.'+id)))return {choice:'unset'};return {choice,id,version:'1'};}
async function consentChoice(req,env,b){strict(b,['choice']);need(['accepted','rejected'].includes(b.choice));need(env.CONSENT_SECRET,'consent_unavailable',503);const ts=now(),id=uid();await stmt(env,'INSERT INTO consent_receipts(id,choice,version,created) VALUES(?,?,?,?)',id,b.choice,'1',ts).run();const value=b.choice+'.'+ts+'.'+id;return json({choice:b.choice},200,{'Set-Cookie':'nc_consent='+value+'.'+await hmac(env.CONSENT_SECRET,value)+'; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=15552000'});}
async function metric(req,env,b){strict(b,['page','locale','kind','key']);need((await consentState(req,env)).choice==='accepted','consent_required',403);need(safePages.includes(b.page)&&['view','engaged'].includes(b.kind)&&validId(b.key),'event_rejected');locale(b.locale);const day=new Date().toISOString().slice(0,10);await db(env).batch([stmt(env,'INSERT OR IGNORE INTO event_keys(id,created) VALUES(?,?)',b.key+'_'+b.kind,now()),stmt(env,'INSERT INTO metrics(day,page,locale,kind,count) SELECT ?,?,?,?,1 WHERE changes()=1 ON CONFLICT(day,page,locale,kind) DO UPDATE SET count=count+1',day,b.page,b.locale,b.kind)]);return json({ok:true});}
async function checkout(req,env,b){const a=actor(req);strict(b,['booking']);const item=await getBooking(env,b.booking,a.id);need(item.status==='active','booking_inactive',409);need(env.STRIPE_SECRET_KEY?.startsWith('sk_test_'),'payment_not_configured',503);need(!item.payment.includes('paid'),'already_processed',409);const url=new URL(req.url),base=url.origin,localePath=item.locale==='nb'?'/':('/'+item.locale+'/');const params=new URLSearchParams({mode:'payment',success_url:base+localePath+'booking/?payment=return',cancel_url:base+localePath+'booking/?payment=cancel','payment_method_types[0]':'card','line_items[0][price_data][currency]':'nok','line_items[0][price_data][unit_amount]':String(item.amount),'line_items[0][price_data][product_data][name]':'NAVIAR CARE 2 — TEST ONLY, no medical service','line_items[0][quantity]':'1','metadata[booking]':item.id,'metadata[purpose]':'technical_test',expires_at:String(Math.floor(now()/1000)+1800)});
const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+env.STRIPE_SECRET_KEY,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':'nc2-checkout-'+item.id},body:params,signal:AbortSignal.timeout(15000)});need(r.ok,'payment_provider_unavailable',502);const s=await r.json();need(typeof s.id==='string'&&s.livemode===false&&s.url&&new URL(s.url).hostname==='checkout.stripe.com','invalid_provider_response',502);const updated=await stmt(env,"UPDATE bookings SET session=?,payment='stripe_test_pending',updated=? WHERE id=? AND status='active' AND payment NOT IN ('stripe_test_paid','test_refund_review')",s.id,now(),item.id).run();need(updated.meta.changes===1,'booking_changed',409);return json({url:s.url,mode:'stripe_test'});}
export async function stripeWebhook(req,env){need(env.STRIPE_WEBHOOK_SECRET&&env.STRIPE_SECRET_KEY?.startsWith('sk_test_'),'payment_not_configured',503);const raw=await req.text();need(raw.length<65536,'request_too_large',413);const parts=(req.headers.get('stripe-signature')||'').split(',');const ts=parts.find(x=>x.startsWith('t='))?.slice(2);need(ts&&Math.abs(now()/1000-Number(ts))<=300,'invalid_signature',400);const sig=await hmac(env.STRIPE_WEBHOOK_SECRET,ts+'.'+raw);need(parts.some(x=>x.startsWith('v1=')&&same(x.slice(3),sig)),'invalid_signature');let evt;try{evt=JSON.parse(raw);}catch{throw new Fault('invalid_json');}need(evt.livemode===false&&validId(evt.id),'live_payment_rejected');const s=evt.data?.object;if(evt.type!=='checkout.session.completed')return json({received:true,ignored:true});need(s?.livemode===false&&s.payment_status==='paid'&&s.metadata?.purpose==='technical_test','invalid_payment_event');const b=await one(env,'SELECT * FROM bookings WHERE id=?',s.metadata.booking||'');if(!b)return json({received:true,ignored:true});need(s.id===b.session&&s.amount_total===b.amount&&s.currency===b.currency,'payment_mismatch');await db(env).batch([stmt(env,'INSERT OR IGNORE INTO webhook_events(id,created,kind) VALUES(?,?,?)',evt.id,now(),evt.type),stmt(env,"UPDATE bookings SET payment=CASE WHEN status='active' THEN 'stripe_test_paid' ELSE 'test_refund_review' END,updated=? WHERE id=? AND changes()=1",now(),b.id)]);return json({received:true});}
async function previewEmail(req,env,id,b){const a=actor(req);strict(b,['send']);const msg=await one(env,'SELECT o.*,b.owner FROM outbox o JOIN bookings b ON o.booking=b.id WHERE o.id=? AND b.owner=?',id,a.id);need(msg,'not_found',404);const template=emailTemplate(msg.kind,msg.locale,msg.starts);if(!b.send)return json({...template,state:msg.state});need(env.EMAIL_TEST_SEND==='enabled'&&env.RESEND_API_KEY&&env.EMAIL_FROM&&env.TEST_RECIPIENT===a.email,'email_not_configured',503);need(msg.state!=='sent','already_processed',409);need(now()-msg.created<23*3600000&&msg.attempts<3,'email_retry_window_closed',409);const locked=await stmt(env,"UPDATE outbox SET state='sending',attempts=attempts+1 WHERE id=? AND state IN ('preview','failed') AND attempts<3",id).run();need(locked.meta.changes===1,'email_in_progress',409);try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':'nc2-email-'+id},body:JSON.stringify({from:env.EMAIL_FROM,to:[a.email],subject:template.subject,text:template.text}),signal:AbortSignal.timeout(15000)});need(r.ok,'email_provider_unavailable',502);const data=await r.json();need(typeof data.id==='string','invalid_provider_response',502);await stmt(env,"UPDATE outbox SET state='sent',providerId=? WHERE id=?",data.id,id).run();return json({state:'sent'});}catch(e){await stmt(env,"UPDATE outbox SET state='failed' WHERE id=?",id).run();throw e;}}
async function maintenance(env){const ts=now();await db(env).batch([stmt(env,'DELETE FROM bookings WHERE updated<?',ts-30*86400000),stmt(env,'DELETE FROM slots WHERE starts<? AND id NOT IN (SELECT slot FROM bookings)',ts-30*86400000),stmt(env,'DELETE FROM event_keys WHERE created<?',ts-86400000),stmt(env,'DELETE FROM metrics WHERE day<?',new Date(ts-90*86400000).toISOString().slice(0,10)),stmt(env,'DELETE FROM consent_receipts WHERE created<?',ts-180*86400000),stmt(env,'DELETE FROM webhook_events WHERE created<?',ts-30*86400000)]);}
export async function api(req,env){try{const path=new URL(req.url).pathname,method=req.method;
if(path==='/api/stripe/webhook'&&method==='POST')return await stripeWebhook(req,env);
if(!['GET','POST'].includes(method))throw new Fault('method_not_allowed',405);
if(method==='POST')origin(req);
if(path==='/api/consent')return method==='GET'?json(await consentState(req,env)):await consentChoice(req,env,await body(req));
if(path==='/api/metrics'&&method==='POST')return await metric(req,env,await body(req));
const a=actor(req);
if(path==='/api/session'&&method==='GET')return json({signedIn:true,admin:!!a.email&&(env.ADMIN_EMAILS||'').toLowerCase().split(',').map(x=>x.trim()).includes(a.email.toLowerCase()),mode:'test',payments:env.STRIPE_SECRET_KEY?.startsWith('sk_test_')?'stripe_test':'unconfigured',email:env.EMAIL_TEST_SEND==='enabled'&&!!env.RESEND_API_KEY?'test_enabled':'preview'});
if(path==='/api/slots'&&method==='GET')return json({slots:await rows(env,"SELECT s.* FROM slots s WHERE s.starts>? AND NOT EXISTS(SELECT 1 FROM bookings b WHERE b.slot=s.id AND b.status='active') ORDER BY s.starts LIMIT 48",now()+60000),timezone:'Europe/Oslo',mode:'test'});
if(path==='/api/bookings'&&method==='POST')return await createBooking(req,env,await body(req));
if(path==='/api/bookings'&&method==='GET')return json({bookings:await rows(env,'SELECT b.id,b.slot,b.locale,b.status,b.payment,b.amount,b.currency,s.starts,s.ends FROM bookings b JOIN slots s ON b.slot=s.id WHERE b.owner=? ORDER BY b.created DESC LIMIT 50',a.id),outbox:await rows(env,'SELECT o.id,o.booking,o.kind,o.locale,o.starts,o.created,o.state FROM outbox o JOIN bookings b ON o.booking=b.id WHERE b.owner=? ORDER BY o.created DESC LIMIT 50',a.id)});
const m=path.match(/^\/api\/bookings\/([a-zA-Z0-9_-]+)(\/calendar)?$/);if(m){if(m[2]&&method==='GET'){const b=await getBooking(env,m[1],a.id);need(b.status==='active','booking_inactive',409);const dt=v=>new Date(v).toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';return new Response(['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//NAVIAR CARE 2//TEST//EN','BEGIN:VEVENT','UID:'+b.id+'@naviar-care-test','DTSTAMP:'+dt(now()),'DTSTART:'+dt(b.starts),'DTEND:'+dt(b.ends),'SUMMARY:NAVIAR CARE 2 - TEST ONLY','DESCRIPTION:Technical test. No medical appointment or video call.','END:VEVENT','END:VCALENDAR',''].join('\r\n'),{headers:{'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':'attachment; filename="naviar-test.ics"','Cache-Control':'no-store'}});}if(method==='POST')return await changeBooking(req,env,m[1],await body(req));}
if(path==='/api/payment/checkout'&&method==='POST')return await checkout(req,env,await body(req));
if(path==='/api/payment/simulate'&&method==='POST'){const b=await body(req);strict(b,['booking','result']);need(['success','failure'].includes(b.result));const item=await getBooking(env,b.booking,a.id);need(item.status==='active'&&!item.session,'payment_in_progress',409);const changed=await stmt(env,"UPDATE bookings SET payment=?,updated=? WHERE id=? AND owner=? AND status='active' AND session IS NULL",'simulated_'+b.result,now(),item.id,a.id).run();need(changed.meta.changes===1,'booking_changed',409);return json({mode:'simulation',charged:false});}
const mail=path.match(/^\/api\/outbox\/([a-zA-Z0-9_-]+)$/);if(mail&&method==='POST')return await previewEmail(req,env,mail[1],await body(req));
if(path.startsWith('/api/admin/')){admin(req,env);if(path==='/api/admin/seed'&&method==='POST'){strict(await body(req),[]);await maintenance(env);await db(env).batch(exampleSlots().map(s=>stmt(env,'INSERT OR IGNORE INTO slots(id,starts,ends) VALUES(?,?,?)',s.id,s.starts,s.ends)));return json({ok:true});}if(path==='/api/admin/summary'&&method==='GET'){await maintenance(env);return json({mode:'test',metrics:await rows(env,'SELECT * FROM metrics ORDER BY day DESC LIMIT 300'),operations:await rows(env,'SELECT status,payment,count(*) AS count FROM bookings GROUP BY status,payment'),outbox:await rows(env,'SELECT state,count(*) AS count FROM outbox GROUP BY state'),forecast:{...forecastContent([]),reason:'All traffic and reservations are tests. No health predictions or individual profiles.'},retentionDays:{bookings:30,aggregates:90,consent:180}});}}
if(path==='/api/my-data'&&method==='POST'){const b=await body(req);strict(b,['delete_test_data']);need(b.delete_test_data===true);await stmt(env,'DELETE FROM bookings WHERE owner=?',a.id).run();return json({deleted:true});}
throw new Fault('not_found',404);
}catch(e){if(e instanceof Fault)return json({error:e.message},e.status);console.error('Naviar operation failed',e.name);return json({error:'service_unavailable'},503);}}
