import {readFile,writeFile,readdir,mkdir,cp,rm} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
const root=process.cwd(),out=resolve(root,'dist'),assets={};
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.webp':'image/webp','.txt':'text/plain; charset=utf-8','.json':'application/json; charset=utf-8'};
await rm(resolve(out,'server'),{recursive:true,force:true});await rm(resolve(out,'.openai'),{recursive:true,force:true});
async function walk(dir){for(const item of await readdir(dir,{withFileTypes:true})){const p=resolve(dir,item.name);if(item.isDirectory())await walk(p);else{const path='/'+p.slice(out.length+1),bytes=await readFile(p);assets[path]={type:types[extname(p)]||'application/octet-stream',base64:bytes.toString('base64')};}}}
await walk(out);await mkdir(resolve(out,'server'),{recursive:true});
await cp(resolve(root,'server/operations.mjs'),resolve(out,'server/operations.mjs'));
await cp(resolve(root,'server/forecast.mjs'),resolve(out,'server/forecast.mjs'));
const source=`import {api} from './operations.mjs';\nconst assets=${JSON.stringify(assets)};\nexport default {async fetch(req,env,ctx){const url=new URL(req.url);let res;if(url.pathname.startsWith('/api/'))res=await api(req,env);else {let p=url.pathname;if(p.endsWith('/'))p+='index.html';else if(!p.split('/').pop().includes('.'))return Response.redirect(url.origin+p+'/',308);const file=assets[p]||assets['/404.html'];res=new Response(req.method==='HEAD'?null:Uint8Array.from(atob(file.base64),c=>c.charCodeAt(0)),{status:assets[p]?200:404,headers:{'Content-Type':file.type,'Cache-Control':'private, no-cache'}});}const h=new Headers(res.headers);h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','no-referrer');h.set('X-Frame-Options','DENY');h.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');h.set('Content-Security-Policy',\"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'\");return new Response(res.body,{status:res.status,headers:h});}};`;
await writeFile(resolve(out,'server/index.js'),source);await mkdir(resolve(out,'.openai'),{recursive:true});await cp(resolve(root,'.openai/hosting.json'),resolve(out,'.openai/hosting.json'));await cp(resolve(root,'drizzle'),resolve(out,'.openai/drizzle'),{recursive:true});console.log('Built Worker with '+Object.keys(assets).length+' embedded assets and D1 migrations.');
