import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const careRequests=sqliteTable('care_requests',{
 id:text('id').primaryKey(),owner:text('owner').notNull(),email:text('email').notNull(),fingerprint:text('fingerprint').notNull(),lang:text('lang').notNull(),name:text('name').notNull(),postcode:text('postcode').notNull(),service:text('service').notNull(),timing:text('timing').notNull(),startsAt:integer('starts_at').notNull(),duration:integer('duration').notNull(),forWhom:text('for_whom').notNull(),consent:integer('consent').notNull().default(0),sharing:text('sharing').notNull().default('none'),status:text('status').notNull(),amount:integer('amount'),paymentState:text('payment_state').notNull().default('unpaid'),checkoutId:text('checkout_id'),paymentAttempt:text('payment_attempt'),checkoutStartedAt:integer('checkout_started_at'),revision:integer('revision').notNull().default(0),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()
},t=>[index('idx_care_requests_owner').on(t.owner,t.createdAt)]);
export const careOutbox=sqliteTable('care_outbox',{id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>careRequests.id,{onDelete:'cascade'}),kind:text('kind').notNull(),status:text('status').notNull().default('preview'),attempts:integer('attempts').notNull().default(0),providerId:text('provider_id'),leaseUntil:integer('lease_until'),nextAttemptAt:integer('next_attempt_at'),firstAttemptAt:integer('first_attempt_at'),lastError:text('last_error'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('idx_care_outbox_status').on(t.status,t.updatedAt)]);
export const careCases=sqliteTable('care_cases',{id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>careRequests.id,{onDelete:'cascade'}),reason:text('reason').notNull(),status:text('status').notNull().default('open'),responsibility:text('responsibility').notNull(),assignedTo:text('assigned_to'),claimedAt:integer('claimed_at'),reviewedAt:integer('reviewed_at'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('uq_care_case_request_reason').on(t.requestId,t.reason)]);
export const careAnalytics=sqliteTable('care_analytics',{id:text('id').primaryKey(),event:text('event').notNull(),section:text('section').notNull(),service:text('service'),lang:text('lang').notNull(),consentVersion:text('consent_version').notNull(),day:text('day').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_care_analytics_day_event').on(t.day,t.event)]);
export const careAudit=sqliteTable('care_audit',{id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>careRequests.id,{onDelete:'cascade'}),actor:text('actor').notNull(),action:text('action').notNull(),createdAt:integer('created_at').notNull()});
export const careApplications=sqliteTable('care_applications',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),postcode:text('postcode').notNull(),services:text('services').notNull(),lang:text('lang').notNull(),status:text('status').notNull().default('unverified'),createdAt:integer('created_at').notNull()},t=>[index('idx_care_applications_owner').on(t.owner)]);
export const carePaymentEvents=sqliteTable('care_payment_events',{id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>careRequests.id,{onDelete:'cascade'}),createdAt:integer('created_at').notNull()});

// Preserve existing tables from the earlier source; no data-destructive migrations.
export * from './legacy-schema';

// A resource code is a test scheduling resource, never evidence of a verified helper.
export const careReservations=sqliteTable('care_reservations',{requestId:text('request_id').primaryKey().references(()=>careRequests.id,{onDelete:'cascade'}),resource:text('resource').notNull(),startsAt:integer('starts_at').notNull(),endsAt:integer('ends_at').notNull(),holdUntil:integer('hold_until').notNull(),state:text('state').notNull().default('held')},t=>[index('idx_care_reservations_resource').on(t.resource,t.startsAt)]);
export const careFeedback=sqliteTable('care_feedback',{id:text('id').primaryKey(),section:text('section').notNull(),lang:text('lang').notNull(),helpful:text('helpful').notNull(),nextNeed:text('next_need').notNull(),day:text('day').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_care_feedback_day').on(t.day)]);
